services:
  database:
    container_name: gophkeeper-database
    image: postgres:${POSTGRES_TAG}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gophkeeper -d gophkeeper"]
      interval: 5s
      retries: 3
      timeout: 5s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "P@ssw0rd"
      POSTGRES_DB: postgres
      POSTGRES_DATA: "/var/lib/postgresql/data"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
      - "gophkeeper-volume:/var/lib/postgresql/data"
    ports:
      - "5434:5432"
    networks:
      - gophkeeper-network
    restart: always

volumes:
  gophkeeper-volume:
    name: gophkeeper-volume

networks:
  gophkeeper-network:
    driver: bridge
    name: gophkeeper-network
