// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: proto/v1/keeper/keeper.proto

package keeperpb

import (
	common "github.com/talx-hub/gophkeeper/proto/v1/common"
	metadata "github.com/talx-hub/gophkeeper/proto/v1/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRequest_SyncMode int32

const (
	SyncRequest_SYNC_MODE_UNSPECIFIED SyncRequest_SyncMode = 0
	SyncRequest_SYNC_MODE_SHORT       SyncRequest_SyncMode = 1 // без бинарных данных
	SyncRequest_SYNC_MODE_FULL        SyncRequest_SyncMode = 2 // полная синхронизация с бинарными данными
)

// Enum value maps for SyncRequest_SyncMode.
var (
	SyncRequest_SyncMode_name = map[int32]string{
		0: "SYNC_MODE_UNSPECIFIED",
		1: "SYNC_MODE_SHORT",
		2: "SYNC_MODE_FULL",
	}
	SyncRequest_SyncMode_value = map[string]int32{
		"SYNC_MODE_UNSPECIFIED": 0,
		"SYNC_MODE_SHORT":       1,
		"SYNC_MODE_FULL":        2,
	}
)

func (x SyncRequest_SyncMode) Enum() *SyncRequest_SyncMode {
	p := new(SyncRequest_SyncMode)
	*p = x
	return p
}

func (x SyncRequest_SyncMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncRequest_SyncMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_keeper_keeper_proto_enumTypes[0].Descriptor()
}

func (SyncRequest_SyncMode) Type() protoreflect.EnumType {
	return &file_proto_v1_keeper_keeper_proto_enumTypes[0]
}

func (x SyncRequest_SyncMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncRequest_SyncMode.Descriptor instead.
func (SyncRequest_SyncMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_keeper_keeper_proto_rawDescGZIP(), []int{0, 0}
}

// Запрос на синхронизацию данных.
// sync_mode определяет режим синхронизации:
// - SYNC_MODE_UNSPECIFIED: режим не выбран (по умолчанию).
// - SYNC_MODE_SHORT: синхронизация без бинарных данных.
// - SYNC_MODE_FULL: полная синхронизация всех данных, включая бинарные.
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncMode      *SyncRequest_SyncMode  `protobuf:"varint,1,opt,name=sync_mode,json=syncMode,enum=gophkeeper.v1.keeper.SyncRequest_SyncMode" json:"sync_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_keeper_keeper_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetSyncMode() SyncRequest_SyncMode {
	if x != nil && x.SyncMode != nil {
		return *x.SyncMode
	}
	return SyncRequest_SYNC_MODE_UNSPECIFIED
}

// Ответ при синхронизации: содержит один объект Data.
// Поток сообщений SyncResponse позволяет серверу поэтапно
// отправлять данные клиенту.
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *metadata.Metadata     `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Payload       *common.Payload        `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_keeper_keeper_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetMetadata() *metadata.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SyncResponse) GetPayload() *common.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Запрос на добавление нового объекта данных.
type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *metadata.Metadata     `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Payload       *common.Payload        `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_keeper_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *AddRequest) GetMetadata() *metadata.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AddRequest) GetPayload() *common.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Ответ сервера на запрос добавления объекта данных.
type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_keeper_keeper_proto_rawDescGZIP(), []int{3}
}

// Запрос получения объекта данных по метаданным.
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *metadata.Metadata     `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_keeper_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetMetadata() *metadata.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Ответ на запрос Get: возвращает полный объект данных.
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *metadata.Metadata     `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	Payload       *common.Payload        `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_keeper_keeper_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetMetadata() *metadata.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetResponse) GetPayload() *common.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Запрос на удаление объекта данных по метаданным.
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *metadata.Metadata     `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_keeper_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetMetadata() *metadata.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Ответ сервера на запрос удаления объекта данных.
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_keeper_keeper_proto_rawDescGZIP(), []int{7}
}

// Запрос на получение списка объектов.
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_keeper_keeper_proto_rawDescGZIP(), []int{8}
}

// Ответ на запрос списка: список метаданных объектов, сохранённых в хранилище.
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      []*metadata.Metadata   `protobuf:"bytes,1,rep,name=metadata" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_keeper_keeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_keeper_keeper_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetMetadata() []*metadata.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_v1_keeper_keeper_proto protoreflect.FileDescriptor

const file_proto_v1_keeper_keeper_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/v1/keeper/keeper.proto\x12\x14gophkeeper.v1.keeper\x1a proto/v1/metadata/metadata.proto\x1a\x1cproto/v1/common/common.proto\"\xa6\x01\n" +
	"\vSyncRequest\x12G\n" +
	"\tsync_mode\x18\x01 \x01(\x0e2*.gophkeeper.v1.keeper.SyncRequest.SyncModeR\bsyncMode\"N\n" +
	"\bSyncMode\x12\x19\n" +
	"\x15SYNC_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSYNC_MODE_SHORT\x10\x01\x12\x12\n" +
	"\x0eSYNC_MODE_FULL\x10\x02\"\x85\x01\n" +
	"\fSyncResponse\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .gophkeeper.v1.metadata.MetadataR\bmetadata\x127\n" +
	"\apayload\x18\x02 \x01(\v2\x1d.gophkeeper.v1.common.PayloadR\apayload\"\x83\x01\n" +
	"\n" +
	"AddRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .gophkeeper.v1.metadata.MetadataR\bmetadata\x127\n" +
	"\apayload\x18\x02 \x01(\v2\x1d.gophkeeper.v1.common.PayloadR\apayload\"\r\n" +
	"\vAddResponse\"J\n" +
	"\n" +
	"GetRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .gophkeeper.v1.metadata.MetadataR\bmetadata\"\x84\x01\n" +
	"\vGetResponse\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .gophkeeper.v1.metadata.MetadataR\bmetadata\x127\n" +
	"\apayload\x18\x02 \x01(\v2\x1d.gophkeeper.v1.common.PayloadR\apayload\"M\n" +
	"\rDeleteRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .gophkeeper.v1.metadata.MetadataR\bmetadata\"\x10\n" +
	"\x0eDeleteResponse\"\r\n" +
	"\vListRequest\"L\n" +
	"\fListResponse\x12<\n" +
	"\bmetadata\x18\x01 \x03(\v2 .gophkeeper.v1.metadata.MetadataR\bmetadata2\x99\x03\n" +
	"\x06Keeper\x12O\n" +
	"\x04Sync\x12!.gophkeeper.v1.keeper.SyncRequest\x1a\".gophkeeper.v1.keeper.SyncResponse0\x01\x12L\n" +
	"\x03Add\x12 .gophkeeper.v1.keeper.AddRequest\x1a!.gophkeeper.v1.keeper.AddResponse(\x01\x12M\n" +
	"\x04List\x12!.gophkeeper.v1.keeper.ListRequest\x1a\".gophkeeper.v1.keeper.ListResponse\x12L\n" +
	"\x03Get\x12 .gophkeeper.v1.keeper.GetRequest\x1a!.gophkeeper.v1.keeper.GetResponse0\x01\x12S\n" +
	"\x06Delete\x12#.gophkeeper.v1.keeper.DeleteRequest\x1a$.gophkeeper.v1.keeper.DeleteResponseB@Z>github.com/talx-hub/gophkeeper/internal/api/v1/keeper;keeperpbb\beditionsp\xe8\a"

var (
	file_proto_v1_keeper_keeper_proto_rawDescOnce sync.Once
	file_proto_v1_keeper_keeper_proto_rawDescData []byte
)

func file_proto_v1_keeper_keeper_proto_rawDescGZIP() []byte {
	file_proto_v1_keeper_keeper_proto_rawDescOnce.Do(func() {
		file_proto_v1_keeper_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_keeper_keeper_proto_rawDesc), len(file_proto_v1_keeper_keeper_proto_rawDesc)))
	})
	return file_proto_v1_keeper_keeper_proto_rawDescData
}

var file_proto_v1_keeper_keeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_keeper_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_v1_keeper_keeper_proto_goTypes = []any{
	(SyncRequest_SyncMode)(0), // 0: gophkeeper.v1.keeper.SyncRequest.SyncMode
	(*SyncRequest)(nil),       // 1: gophkeeper.v1.keeper.SyncRequest
	(*SyncResponse)(nil),      // 2: gophkeeper.v1.keeper.SyncResponse
	(*AddRequest)(nil),        // 3: gophkeeper.v1.keeper.AddRequest
	(*AddResponse)(nil),       // 4: gophkeeper.v1.keeper.AddResponse
	(*GetRequest)(nil),        // 5: gophkeeper.v1.keeper.GetRequest
	(*GetResponse)(nil),       // 6: gophkeeper.v1.keeper.GetResponse
	(*DeleteRequest)(nil),     // 7: gophkeeper.v1.keeper.DeleteRequest
	(*DeleteResponse)(nil),    // 8: gophkeeper.v1.keeper.DeleteResponse
	(*ListRequest)(nil),       // 9: gophkeeper.v1.keeper.ListRequest
	(*ListResponse)(nil),      // 10: gophkeeper.v1.keeper.ListResponse
	(*metadata.Metadata)(nil), // 11: gophkeeper.v1.metadata.Metadata
	(*common.Payload)(nil),    // 12: gophkeeper.v1.common.Payload
}
var file_proto_v1_keeper_keeper_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.v1.keeper.SyncRequest.sync_mode:type_name -> gophkeeper.v1.keeper.SyncRequest.SyncMode
	11, // 1: gophkeeper.v1.keeper.SyncResponse.metadata:type_name -> gophkeeper.v1.metadata.Metadata
	12, // 2: gophkeeper.v1.keeper.SyncResponse.payload:type_name -> gophkeeper.v1.common.Payload
	11, // 3: gophkeeper.v1.keeper.AddRequest.metadata:type_name -> gophkeeper.v1.metadata.Metadata
	12, // 4: gophkeeper.v1.keeper.AddRequest.payload:type_name -> gophkeeper.v1.common.Payload
	11, // 5: gophkeeper.v1.keeper.GetRequest.metadata:type_name -> gophkeeper.v1.metadata.Metadata
	11, // 6: gophkeeper.v1.keeper.GetResponse.metadata:type_name -> gophkeeper.v1.metadata.Metadata
	12, // 7: gophkeeper.v1.keeper.GetResponse.payload:type_name -> gophkeeper.v1.common.Payload
	11, // 8: gophkeeper.v1.keeper.DeleteRequest.metadata:type_name -> gophkeeper.v1.metadata.Metadata
	11, // 9: gophkeeper.v1.keeper.ListResponse.metadata:type_name -> gophkeeper.v1.metadata.Metadata
	1,  // 10: gophkeeper.v1.keeper.Keeper.Sync:input_type -> gophkeeper.v1.keeper.SyncRequest
	3,  // 11: gophkeeper.v1.keeper.Keeper.Add:input_type -> gophkeeper.v1.keeper.AddRequest
	9,  // 12: gophkeeper.v1.keeper.Keeper.List:input_type -> gophkeeper.v1.keeper.ListRequest
	5,  // 13: gophkeeper.v1.keeper.Keeper.Get:input_type -> gophkeeper.v1.keeper.GetRequest
	7,  // 14: gophkeeper.v1.keeper.Keeper.Delete:input_type -> gophkeeper.v1.keeper.DeleteRequest
	2,  // 15: gophkeeper.v1.keeper.Keeper.Sync:output_type -> gophkeeper.v1.keeper.SyncResponse
	4,  // 16: gophkeeper.v1.keeper.Keeper.Add:output_type -> gophkeeper.v1.keeper.AddResponse
	10, // 17: gophkeeper.v1.keeper.Keeper.List:output_type -> gophkeeper.v1.keeper.ListResponse
	6,  // 18: gophkeeper.v1.keeper.Keeper.Get:output_type -> gophkeeper.v1.keeper.GetResponse
	8,  // 19: gophkeeper.v1.keeper.Keeper.Delete:output_type -> gophkeeper.v1.keeper.DeleteResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_v1_keeper_keeper_proto_init() }
func file_proto_v1_keeper_keeper_proto_init() {
	if File_proto_v1_keeper_keeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_keeper_keeper_proto_rawDesc), len(file_proto_v1_keeper_keeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_keeper_keeper_proto_goTypes,
		DependencyIndexes: file_proto_v1_keeper_keeper_proto_depIdxs,
		EnumInfos:         file_proto_v1_keeper_keeper_proto_enumTypes,
		MessageInfos:      file_proto_v1_keeper_keeper_proto_msgTypes,
	}.Build()
	File_proto_v1_keeper_keeper_proto = out.File
	file_proto_v1_keeper_keeper_proto_goTypes = nil
	file_proto_v1_keeper_keeper_proto_depIdxs = nil
}
