// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/talx-hub/gophkeeper/internal/model"
	"github.com/talx-hub/gophkeeper/internal/service/server/keeper"
)

// NewMockKeeperUseCase creates a new instance of MockKeeperUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeeperUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeeperUseCase {
	mock := &MockKeeperUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeeperUseCase is an autogenerated mock type for the KeeperUseCase type
type MockKeeperUseCase struct {
	mock.Mock
}

type MockKeeperUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeeperUseCase) EXPECT() *MockKeeperUseCase_Expecter {
	return &MockKeeperUseCase_Expecter{mock: &_m.Mock}
}

// AddSealed provides a mock function for the type MockKeeperUseCase
func (_mock *MockKeeperUseCase) AddSealed(ctx context.Context, userID model.UserID, meta *model.Metadata, sealed []byte) (model.DataID, error) {
	ret := _mock.Called(ctx, userID, meta, sealed)

	if len(ret) == 0 {
		panic("no return value specified for AddSealed")
	}

	var r0 model.DataID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID, *model.Metadata, []byte) (model.DataID, error)); ok {
		return returnFunc(ctx, userID, meta, sealed)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID, *model.Metadata, []byte) model.DataID); ok {
		r0 = returnFunc(ctx, userID, meta, sealed)
	} else {
		r0 = ret.Get(0).(model.DataID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserID, *model.Metadata, []byte) error); ok {
		r1 = returnFunc(ctx, userID, meta, sealed)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeeperUseCase_AddSealed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSealed'
type MockKeeperUseCase_AddSealed_Call struct {
	*mock.Call
}

// AddSealed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model.UserID
//   - meta *model.Metadata
//   - sealed []byte
func (_e *MockKeeperUseCase_Expecter) AddSealed(ctx interface{}, userID interface{}, meta interface{}, sealed interface{}) *MockKeeperUseCase_AddSealed_Call {
	return &MockKeeperUseCase_AddSealed_Call{Call: _e.mock.On("AddSealed", ctx, userID, meta, sealed)}
}

func (_c *MockKeeperUseCase_AddSealed_Call) Run(run func(ctx context.Context, userID model.UserID, meta *model.Metadata, sealed []byte)) *MockKeeperUseCase_AddSealed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserID
		if args[1] != nil {
			arg1 = args[1].(model.UserID)
		}
		var arg2 *model.Metadata
		if args[2] != nil {
			arg2 = args[2].(*model.Metadata)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKeeperUseCase_AddSealed_Call) Return(dataID model.DataID, err error) *MockKeeperUseCase_AddSealed_Call {
	_c.Call.Return(dataID, err)
	return _c
}

func (_c *MockKeeperUseCase_AddSealed_Call) RunAndReturn(run func(ctx context.Context, userID model.UserID, meta *model.Metadata, sealed []byte) (model.DataID, error)) *MockKeeperUseCase_AddSealed_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockKeeperUseCase
func (_mock *MockKeeperUseCase) Delete(ctx context.Context, id model.DataID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.DataID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperUseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockKeeperUseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id model.DataID
func (_e *MockKeeperUseCase_Expecter) Delete(ctx interface{}, id interface{}) *MockKeeperUseCase_Delete_Call {
	return &MockKeeperUseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockKeeperUseCase_Delete_Call) Run(run func(ctx context.Context, id model.DataID)) *MockKeeperUseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.DataID
		if args[1] != nil {
			arg1 = args[1].(model.DataID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeeperUseCase_Delete_Call) Return(err error) *MockKeeperUseCase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperUseCase_Delete_Call) RunAndReturn(run func(ctx context.Context, id model.DataID) error) *MockKeeperUseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetSealed provides a mock function for the type MockKeeperUseCase
func (_mock *MockKeeperUseCase) GetSealed(ctx context.Context, id model.DataID, callback keeper.StreamCallback) error {
	ret := _mock.Called(ctx, id, callback)

	if len(ret) == 0 {
		panic("no return value specified for GetSealed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.DataID, keeper.StreamCallback) error); ok {
		r0 = returnFunc(ctx, id, callback)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperUseCase_GetSealed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSealed'
type MockKeeperUseCase_GetSealed_Call struct {
	*mock.Call
}

// GetSealed is a helper method to define mock.On call
//   - ctx context.Context
//   - id model.DataID
//   - callback keeper.StreamCallback
func (_e *MockKeeperUseCase_Expecter) GetSealed(ctx interface{}, id interface{}, callback interface{}) *MockKeeperUseCase_GetSealed_Call {
	return &MockKeeperUseCase_GetSealed_Call{Call: _e.mock.On("GetSealed", ctx, id, callback)}
}

func (_c *MockKeeperUseCase_GetSealed_Call) Run(run func(ctx context.Context, id model.DataID, callback keeper.StreamCallback)) *MockKeeperUseCase_GetSealed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.DataID
		if args[1] != nil {
			arg1 = args[1].(model.DataID)
		}
		var arg2 keeper.StreamCallback
		if args[2] != nil {
			arg2 = args[2].(keeper.StreamCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeeperUseCase_GetSealed_Call) Return(err error) *MockKeeperUseCase_GetSealed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperUseCase_GetSealed_Call) RunAndReturn(run func(ctx context.Context, id model.DataID, callback keeper.StreamCallback) error) *MockKeeperUseCase_GetSealed_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockKeeperUseCase
func (_mock *MockKeeperUseCase) List(ctx context.Context, userID model.UserID) ([]model.MetaLoc, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.MetaLoc
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID) ([]model.MetaLoc, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID) []model.MetaLoc); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MetaLoc)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeeperUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockKeeperUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model.UserID
func (_e *MockKeeperUseCase_Expecter) List(ctx interface{}, userID interface{}) *MockKeeperUseCase_List_Call {
	return &MockKeeperUseCase_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockKeeperUseCase_List_Call) Run(run func(ctx context.Context, userID model.UserID)) *MockKeeperUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserID
		if args[1] != nil {
			arg1 = args[1].(model.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeeperUseCase_List_Call) Return(metaLocs []model.MetaLoc, err error) *MockKeeperUseCase_List_Call {
	_c.Call.Return(metaLocs, err)
	return _c
}

func (_c *MockKeeperUseCase_List_Call) RunAndReturn(run func(ctx context.Context, userID model.UserID) ([]model.MetaLoc, error)) *MockKeeperUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockKeeperUseCase
func (_mock *MockKeeperUseCase) Sync(ctx context.Context, userID model.UserID, mode keeper.SyncMode, callback keeper.StreamCallback) error {
	ret := _mock.Called(ctx, userID, mode, callback)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID, keeper.SyncMode, keeper.StreamCallback) error); ok {
		r0 = returnFunc(ctx, userID, mode, callback)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeeperUseCase_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockKeeperUseCase_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model.UserID
//   - mode keeper.SyncMode
//   - callback keeper.StreamCallback
func (_e *MockKeeperUseCase_Expecter) Sync(ctx interface{}, userID interface{}, mode interface{}, callback interface{}) *MockKeeperUseCase_Sync_Call {
	return &MockKeeperUseCase_Sync_Call{Call: _e.mock.On("Sync", ctx, userID, mode, callback)}
}

func (_c *MockKeeperUseCase_Sync_Call) Run(run func(ctx context.Context, userID model.UserID, mode keeper.SyncMode, callback keeper.StreamCallback)) *MockKeeperUseCase_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserID
		if args[1] != nil {
			arg1 = args[1].(model.UserID)
		}
		var arg2 keeper.SyncMode
		if args[2] != nil {
			arg2 = args[2].(keeper.SyncMode)
		}
		var arg3 keeper.StreamCallback
		if args[3] != nil {
			arg3 = args[3].(keeper.StreamCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockKeeperUseCase_Sync_Call) Return(err error) *MockKeeperUseCase_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeeperUseCase_Sync_Call) RunAndReturn(run func(ctx context.Context, userID model.UserID, mode keeper.SyncMode, callback keeper.StreamCallback) error) *MockKeeperUseCase_Sync_Call {
	_c.Call.Return(run)
	return _c
}
