// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/talx-hub/gophkeeper/internal/model"
)

// NewMockSessionManager creates a new instance of MockSessionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionManager {
	mock := &MockSessionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionManager is an autogenerated mock type for the SessionManager type
type MockSessionManager struct {
	mock.Mock
}

type MockSessionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionManager) EXPECT() *MockSessionManager_Expecter {
	return &MockSessionManager_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) CreateSession(ctx context.Context, userID model.UserID) (string, []byte, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID) (string, []byte, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserID) []byte); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, model.UserID) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSessionManager_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionManager_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model.UserID
func (_e *MockSessionManager_Expecter) CreateSession(ctx interface{}, userID interface{}) *MockSessionManager_CreateSession_Call {
	return &MockSessionManager_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID)}
}

func (_c *MockSessionManager_CreateSession_Call) Run(run func(ctx context.Context, userID model.UserID)) *MockSessionManager_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserID
		if args[1] != nil {
			arg1 = args[1].(model.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionManager_CreateSession_Call) Return(accessToken string, refreshToken []byte, err error) *MockSessionManager_CreateSession_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *MockSessionManager_CreateSession_Call) RunAndReturn(run func(ctx context.Context, userID model.UserID) (string, []byte, error)) *MockSessionManager_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshSession provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) RefreshSession(ctx context.Context, userID model.UserID, refreshToken []byte) (string, []byte, error) {
	ret := _mock.Called(ctx, userID, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshSession")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID, []byte) (string, []byte, error)); ok {
		return returnFunc(ctx, userID, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID, []byte) string); ok {
		r0 = returnFunc(ctx, userID, refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserID, []byte) []byte); ok {
		r1 = returnFunc(ctx, userID, refreshToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, model.UserID, []byte) error); ok {
		r2 = returnFunc(ctx, userID, refreshToken)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSessionManager_RefreshSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshSession'
type MockSessionManager_RefreshSession_Call struct {
	*mock.Call
}

// RefreshSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model.UserID
//   - refreshToken []byte
func (_e *MockSessionManager_Expecter) RefreshSession(ctx interface{}, userID interface{}, refreshToken interface{}) *MockSessionManager_RefreshSession_Call {
	return &MockSessionManager_RefreshSession_Call{Call: _e.mock.On("RefreshSession", ctx, userID, refreshToken)}
}

func (_c *MockSessionManager_RefreshSession_Call) Run(run func(ctx context.Context, userID model.UserID, refreshToken []byte)) *MockSessionManager_RefreshSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserID
		if args[1] != nil {
			arg1 = args[1].(model.UserID)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionManager_RefreshSession_Call) Return(newAccessToken string, newRefreshToken []byte, err error) *MockSessionManager_RefreshSession_Call {
	_c.Call.Return(newAccessToken, newRefreshToken, err)
	return _c
}

func (_c *MockSessionManager_RefreshSession_Call) RunAndReturn(run func(ctx context.Context, userID model.UserID, refreshToken []byte) (string, []byte, error)) *MockSessionManager_RefreshSession_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) RevokeSession(ctx context.Context, refreshToken []byte) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionManager_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockSessionManager_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken []byte
func (_e *MockSessionManager_Expecter) RevokeSession(ctx interface{}, refreshToken interface{}) *MockSessionManager_RevokeSession_Call {
	return &MockSessionManager_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, refreshToken)}
}

func (_c *MockSessionManager_RevokeSession_Call) Run(run func(ctx context.Context, refreshToken []byte)) *MockSessionManager_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionManager_RevokeSession_Call) Return(err error) *MockSessionManager_RevokeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionManager_RevokeSession_Call) RunAndReturn(run func(ctx context.Context, refreshToken []byte) error) *MockSessionManager_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type MockSessionManager
func (_mock *MockSessionManager) ValidateAccessToken(ctx context.Context, token string) (model.UserID, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 model.UserID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.UserID, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.UserID); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(model.UserID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionManager_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockSessionManager_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSessionManager_Expecter) ValidateAccessToken(ctx interface{}, token interface{}) *MockSessionManager_ValidateAccessToken_Call {
	return &MockSessionManager_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, token)}
}

func (_c *MockSessionManager_ValidateAccessToken_Call) Run(run func(ctx context.Context, token string)) *MockSessionManager_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionManager_ValidateAccessToken_Call) Return(userID model.UserID, err error) *MockSessionManager_ValidateAccessToken_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *MockSessionManager_ValidateAccessToken_Call) RunAndReturn(run func(ctx context.Context, token string) (model.UserID, error)) *MockSessionManager_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
