// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/talx-hub/gophkeeper/internal/model"
)

// NewMockSessionService creates a new instance of MockSessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionService {
	mock := &MockSessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionService is an autogenerated mock type for the SessionService type
type MockSessionService struct {
	mock.Mock
}

type MockSessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionService) EXPECT() *MockSessionService_Expecter {
	return &MockSessionService_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockSessionService
func (_mock *MockSessionService) CreateSession(ctx context.Context, userID model.UserID) (string, string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID) (string, string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserID) string); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, model.UserID) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSessionService_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionService_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model.UserID
func (_e *MockSessionService_Expecter) CreateSession(ctx interface{}, userID interface{}) *MockSessionService_CreateSession_Call {
	return &MockSessionService_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID)}
}

func (_c *MockSessionService_CreateSession_Call) Run(run func(ctx context.Context, userID model.UserID)) *MockSessionService_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserID
		if args[1] != nil {
			arg1 = args[1].(model.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionService_CreateSession_Call) Return(accessToken string, refreshToken string, err error) *MockSessionService_CreateSession_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *MockSessionService_CreateSession_Call) RunAndReturn(run func(ctx context.Context, userID model.UserID) (string, string, error)) *MockSessionService_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshSession provides a mock function for the type MockSessionService
func (_mock *MockSessionService) RefreshSession(ctx context.Context, refreshToken string) (string, string, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshSession")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, refreshToken)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSessionService_RefreshSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshSession'
type MockSessionService_RefreshSession_Call struct {
	*mock.Call
}

// RefreshSession is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockSessionService_Expecter) RefreshSession(ctx interface{}, refreshToken interface{}) *MockSessionService_RefreshSession_Call {
	return &MockSessionService_RefreshSession_Call{Call: _e.mock.On("RefreshSession", ctx, refreshToken)}
}

func (_c *MockSessionService_RefreshSession_Call) Run(run func(ctx context.Context, refreshToken string)) *MockSessionService_RefreshSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionService_RefreshSession_Call) Return(newAccessToken string, newRefreshToken string, err error) *MockSessionService_RefreshSession_Call {
	_c.Call.Return(newAccessToken, newRefreshToken, err)
	return _c
}

func (_c *MockSessionService_RefreshSession_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (string, string, error)) *MockSessionService_RefreshSession_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function for the type MockSessionService
func (_mock *MockSessionService) RevokeSession(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionService_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockSessionService_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockSessionService_Expecter) RevokeSession(ctx interface{}, refreshToken interface{}) *MockSessionService_RevokeSession_Call {
	return &MockSessionService_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, refreshToken)}
}

func (_c *MockSessionService_RevokeSession_Call) Run(run func(ctx context.Context, refreshToken string)) *MockSessionService_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionService_RevokeSession_Call) Return(err error) *MockSessionService_RevokeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionService_RevokeSession_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *MockSessionService_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type MockSessionService
func (_mock *MockSessionService) ValidateAccessToken(ctx context.Context, token string) (model.UserID, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 model.UserID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.UserID, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.UserID); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(model.UserID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionService_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockSessionService_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSessionService_Expecter) ValidateAccessToken(ctx interface{}, token interface{}) *MockSessionService_ValidateAccessToken_Call {
	return &MockSessionService_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, token)}
}

func (_c *MockSessionService_ValidateAccessToken_Call) Run(run func(ctx context.Context, token string)) *MockSessionService_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionService_ValidateAccessToken_Call) Return(userID model.UserID, err error) *MockSessionService_ValidateAccessToken_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *MockSessionService_ValidateAccessToken_Call) RunAndReturn(run func(ctx context.Context, token string) (model.UserID, error)) *MockSessionService_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
