// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/talx-hub/gophkeeper/internal/model"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(ctx context.Context, u *model.User) (model.UserID, error) {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.UserID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) (model.UserID, error)); ok {
		return returnFunc(ctx, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) model.UserID); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Get(0).(model.UserID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = returnFunc(ctx, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u *model.User
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, u interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, u *model.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.User
		if args[1] != nil {
			arg1 = args[1].(*model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(userID model.UserID, err error) *MockUserRepository_Create_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, u *model.User) (model.UserID, error)) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Delete(ctx context.Context, uuid model.UserID) error {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID) error); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid model.UserID
func (_e *MockUserRepository_Expecter) Delete(ctx interface{}, uuid interface{}) *MockUserRepository_Delete_Call {
	return &MockUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, uuid)}
}

func (_c *MockUserRepository_Delete_Call) Run(run func(ctx context.Context, uuid model.UserID)) *MockUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserID
		if args[1] != nil {
			arg1 = args[1].(model.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Delete_Call) Return(err error) *MockUserRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, uuid model.UserID) error) *MockUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByID(ctx context.Context, uuid model.UserID) (model.User, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID) (model.User, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID) model.User); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserID) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid model.UserID
func (_e *MockUserRepository_Expecter) FindByID(ctx interface{}, uuid interface{}) *MockUserRepository_FindByID_Call {
	return &MockUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, uuid)}
}

func (_c *MockUserRepository_FindByID_Call) Run(run func(ctx context.Context, uuid model.UserID)) *MockUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserID
		if args[1] != nil {
			arg1 = args[1].(model.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByID_Call) Return(user model.User, err error) *MockUserRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, uuid model.UserID) (model.User, error)) *MockUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLogin provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByLogin(ctx context.Context, loginHash []byte) (model.UserID, model.User, error) {
	ret := _mock.Called(ctx, loginHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByLogin")
	}

	var r0 model.UserID
	var r1 model.User
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (model.UserID, model.User, error)); ok {
		return returnFunc(ctx, loginHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) model.UserID); ok {
		r0 = returnFunc(ctx, loginHash)
	} else {
		r0 = ret.Get(0).(model.UserID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) model.User); ok {
		r1 = returnFunc(ctx, loginHash)
	} else {
		r1 = ret.Get(1).(model.User)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []byte) error); ok {
		r2 = returnFunc(ctx, loginHash)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserRepository_FindByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLogin'
type MockUserRepository_FindByLogin_Call struct {
	*mock.Call
}

// FindByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - loginHash []byte
func (_e *MockUserRepository_Expecter) FindByLogin(ctx interface{}, loginHash interface{}) *MockUserRepository_FindByLogin_Call {
	return &MockUserRepository_FindByLogin_Call{Call: _e.mock.On("FindByLogin", ctx, loginHash)}
}

func (_c *MockUserRepository_FindByLogin_Call) Run(run func(ctx context.Context, loginHash []byte)) *MockUserRepository_FindByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByLogin_Call) Return(userID model.UserID, user model.User, err error) *MockUserRepository_FindByLogin_Call {
	_c.Call.Return(userID, user, err)
	return _c
}

func (_c *MockUserRepository_FindByLogin_Call) RunAndReturn(run func(ctx context.Context, loginHash []byte) (model.UserID, model.User, error)) *MockUserRepository_FindByLogin_Call {
	_c.Call.Return(run)
	return _c
}
