// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: proto/v1/agent/agent.proto

package agent

import (
	common "github.com/talx-hub/gophkeeper/proto/v1/common"
	metadata "github.com/talx-hub/gophkeeper/proto/v1/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Основной объект данных, используемый и шифруемый агентом.
// Каждое сообщение содержит метаданные и один из возможных типов данных.
type UnencryptedData struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *metadata.Metadata     `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*UnencryptedData_AuthData
	//	*UnencryptedData_CardInfo
	//	*UnencryptedData_Payload
	Type          isUnencryptedData_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnencryptedData) Reset() {
	*x = UnencryptedData{}
	mi := &file_proto_v1_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnencryptedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnencryptedData) ProtoMessage() {}

func (x *UnencryptedData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnencryptedData.ProtoReflect.Descriptor instead.
func (*UnencryptedData) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *UnencryptedData) GetMetadata() *metadata.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UnencryptedData) GetType() isUnencryptedData_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *UnencryptedData) GetAuthData() *AuthData {
	if x != nil {
		if x, ok := x.Type.(*UnencryptedData_AuthData); ok {
			return x.AuthData
		}
	}
	return nil
}

func (x *UnencryptedData) GetCardInfo() *CardInfo {
	if x != nil {
		if x, ok := x.Type.(*UnencryptedData_CardInfo); ok {
			return x.CardInfo
		}
	}
	return nil
}

func (x *UnencryptedData) GetPayload() *common.Payload {
	if x != nil {
		if x, ok := x.Type.(*UnencryptedData_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isUnencryptedData_Type interface {
	isUnencryptedData_Type()
}

type UnencryptedData_AuthData struct {
	AuthData *AuthData `protobuf:"bytes,2,opt,name=auth_data,json=authData,oneof"` // данные сайтов и сервисов
}

type UnencryptedData_CardInfo struct {
	CardInfo *CardInfo `protobuf:"bytes,3,opt,name=card_info,json=cardInfo,oneof"` // данные банковских карт
}

type UnencryptedData_Payload struct {
	Payload *common.Payload `protobuf:"bytes,4,opt,name=payload,oneof"` // часть бинарного файла
}

func (*UnencryptedData_AuthData) isUnencryptedData_Type() {}

func (*UnencryptedData_CardInfo) isUnencryptedData_Type() {}

func (*UnencryptedData_Payload) isUnencryptedData_Type() {}

// Данные сайтов или сервисов: логин и пароль.
type AuthData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthData) Reset() {
	*x = AuthData{}
	mi := &file_proto_v1_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthData) ProtoMessage() {}

func (x *AuthData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthData.ProtoReflect.Descriptor instead.
func (*AuthData) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AuthData) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *AuthData) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

// Информация по банковской карте: номер, дата выпуска, имя и фамилия владельца.
type CardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    *string                `protobuf:"bytes,1,opt,name=card_number,json=cardNumber" json:"card_number,omitempty"`
	Expiry        *string                `protobuf:"bytes,2,opt,name=expiry" json:"expiry,omitempty"`
	Owner         *string                `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardInfo) Reset() {
	*x = CardInfo{}
	mi := &file_proto_v1_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInfo) ProtoMessage() {}

func (x *CardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInfo.ProtoReflect.Descriptor instead.
func (*CardInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CardInfo) GetCardNumber() string {
	if x != nil && x.CardNumber != nil {
		return *x.CardNumber
	}
	return ""
}

func (x *CardInfo) GetExpiry() string {
	if x != nil && x.Expiry != nil {
		return *x.Expiry
	}
	return ""
}

func (x *CardInfo) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

var File_proto_v1_agent_agent_proto protoreflect.FileDescriptor

const file_proto_v1_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/v1/agent/agent.proto\x12\x13gophkeeper.v1.agent\x1a proto/v1/metadata/metadata.proto\x1a\x1cproto/v1/common/common.proto\"\x8e\x02\n" +
	"\x0fUnencryptedData\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .gophkeeper.v1.metadata.MetadataR\bmetadata\x12<\n" +
	"\tauth_data\x18\x02 \x01(\v2\x1d.gophkeeper.v1.agent.AuthDataH\x00R\bauthData\x12<\n" +
	"\tcard_info\x18\x03 \x01(\v2\x1d.gophkeeper.v1.agent.CardInfoH\x00R\bcardInfo\x129\n" +
	"\apayload\x18\x04 \x01(\v2\x1d.gophkeeper.v1.common.PayloadH\x00R\apayloadB\x06\n" +
	"\x04type\"B\n" +
	"\bAuthData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Y\n" +
	"\bCardInfo\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x16\n" +
	"\x06expiry\x18\x02 \x01(\tR\x06expiry\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05ownerB5Z3github.com/talx-hub/gophkeeper/internal/model/agentb\beditionsp\xe8\a"

var (
	file_proto_v1_agent_agent_proto_rawDescOnce sync.Once
	file_proto_v1_agent_agent_proto_rawDescData []byte
)

func file_proto_v1_agent_agent_proto_rawDescGZIP() []byte {
	file_proto_v1_agent_agent_proto_rawDescOnce.Do(func() {
		file_proto_v1_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_agent_agent_proto_rawDesc), len(file_proto_v1_agent_agent_proto_rawDesc)))
	})
	return file_proto_v1_agent_agent_proto_rawDescData
}

var file_proto_v1_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_v1_agent_agent_proto_goTypes = []any{
	(*UnencryptedData)(nil),   // 0: gophkeeper.v1.agent.UnencryptedData
	(*AuthData)(nil),          // 1: gophkeeper.v1.agent.AuthData
	(*CardInfo)(nil),          // 2: gophkeeper.v1.agent.CardInfo
	(*metadata.Metadata)(nil), // 3: gophkeeper.v1.metadata.Metadata
	(*common.Payload)(nil),    // 4: gophkeeper.v1.common.Payload
}
var file_proto_v1_agent_agent_proto_depIdxs = []int32{
	3, // 0: gophkeeper.v1.agent.UnencryptedData.metadata:type_name -> gophkeeper.v1.metadata.Metadata
	1, // 1: gophkeeper.v1.agent.UnencryptedData.auth_data:type_name -> gophkeeper.v1.agent.AuthData
	2, // 2: gophkeeper.v1.agent.UnencryptedData.card_info:type_name -> gophkeeper.v1.agent.CardInfo
	4, // 3: gophkeeper.v1.agent.UnencryptedData.payload:type_name -> gophkeeper.v1.common.Payload
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_agent_agent_proto_init() }
func file_proto_v1_agent_agent_proto_init() {
	if File_proto_v1_agent_agent_proto != nil {
		return
	}
	file_proto_v1_agent_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*UnencryptedData_AuthData)(nil),
		(*UnencryptedData_CardInfo)(nil),
		(*UnencryptedData_Payload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_agent_agent_proto_rawDesc), len(file_proto_v1_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_agent_agent_proto_goTypes,
		DependencyIndexes: file_proto_v1_agent_agent_proto_depIdxs,
		MessageInfos:      file_proto_v1_agent_agent_proto_msgTypes,
	}.Build()
	File_proto_v1_agent_agent_proto = out.File
	file_proto_v1_agent_agent_proto_goTypes = nil
	file_proto_v1_agent_agent_proto_depIdxs = nil
}
