// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: proto/v1/health/health.proto

package health

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_v1_health_health_proto protoreflect.FileDescriptor

const file_proto_v1_health_health_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/v1/health/health.proto\x12\x14gophkeeper.v1.health\x1a\x1bgoogle/protobuf/empty.proto2G\n" +
	"\rHealthService\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB.Z,github.com/talx-hub/gophkeeper/api/v1/healthb\beditionsp\xe8\a"

var file_proto_v1_health_health_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
}
var file_proto_v1_health_health_proto_depIdxs = []int32{
	0, // 0: gophkeeper.v1.health.HealthService.Ping:input_type -> google.protobuf.Empty
	0, // 1: gophkeeper.v1.health.HealthService.Ping:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_health_health_proto_init() }
func file_proto_v1_health_health_proto_init() {
	if File_proto_v1_health_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_health_health_proto_rawDesc), len(file_proto_v1_health_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_health_health_proto_goTypes,
		DependencyIndexes: file_proto_v1_health_health_proto_depIdxs,
	}.Build()
	File_proto_v1_health_health_proto = out.File
	file_proto_v1_health_health_proto_goTypes = nil
	file_proto_v1_health_health_proto_depIdxs = nil
}
