// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: proto/v1/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata_DataType int32

const (
	Metadata_DATA_TYPE_UNSPECIFIED Metadata_DataType = 0
	Metadata_DATA_TYPE_AUTH        Metadata_DataType = 1
	Metadata_DATA_TYPE_CARD        Metadata_DataType = 2
	Metadata_DATA_TYPE_BINARY      Metadata_DataType = 3
)

// Enum value maps for Metadata_DataType.
var (
	Metadata_DataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_AUTH",
		2: "DATA_TYPE_CARD",
		3: "DATA_TYPE_BINARY",
	}
	Metadata_DataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED": 0,
		"DATA_TYPE_AUTH":        1,
		"DATA_TYPE_CARD":        2,
		"DATA_TYPE_BINARY":      3,
	}
)

func (x Metadata_DataType) Enum() *Metadata_DataType {
	p := new(Metadata_DataType)
	*p = x
	return p
}

func (x Metadata_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metadata_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_common_proto_enumTypes[0].Descriptor()
}

func (Metadata_DataType) Type() protoreflect.EnumType {
	return &file_proto_v1_common_proto_enumTypes[0]
}

func (x Metadata_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metadata_DataType.Descriptor instead.
func (Metadata_DataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_common_proto_rawDescGZIP(), []int{0, 0}
}

// Метаданные, описывающие объект данных.
// Здесь хранится основная информация для идентификации объекта.
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      *Metadata_DataType     `protobuf:"varint,1,opt,name=data_type,json=dataType,enum=gophkeeper.v1.common.Metadata_DataType" json:"data_type,omitempty"` // Один из типов хранимых данных
	Uuid          *string                `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`                                                                      // Уникальный идентификатор записи
	Name          *string                `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`                                                                      // Человекочитаемое имя
	Description   *string                `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`                                                        // Заметка
	CreatedAt     *int64                 `protobuf:"varint,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`                                          // Время создания (unix timestamp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetDataType() Metadata_DataType {
	if x != nil && x.DataType != nil {
		return *x.DataType
	}
	return Metadata_DATA_TYPE_UNSPECIFIED
}

func (x *Metadata) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *Metadata) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Metadata) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Metadata) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

var File_proto_v1_common_proto protoreflect.FileDescriptor

const file_proto_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/common.proto\x12\x14gophkeeper.v1.common\"\x9e\x02\n" +
	"\bMetadata\x12D\n" +
	"\tdata_type\x18\x01 \x01(\x0e2'.gophkeeper.v1.common.Metadata.DataTypeR\bdataType\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"c\n" +
	"\bDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDATA_TYPE_AUTH\x10\x01\x12\x12\n" +
	"\x0eDATA_TYPE_CARD\x10\x02\x12\x14\n" +
	"\x10DATA_TYPE_BINARY\x10\x03B6Z4github.com/talx-hub/gophkeeper/internal/model/commonb\beditionsp\xe8\a"

var (
	file_proto_v1_common_proto_rawDescOnce sync.Once
	file_proto_v1_common_proto_rawDescData []byte
)

func file_proto_v1_common_proto_rawDescGZIP() []byte {
	file_proto_v1_common_proto_rawDescOnce.Do(func() {
		file_proto_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_common_proto_rawDesc), len(file_proto_v1_common_proto_rawDesc)))
	})
	return file_proto_v1_common_proto_rawDescData
}

var file_proto_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_common_proto_goTypes = []any{
	(Metadata_DataType)(0), // 0: gophkeeper.v1.common.Metadata.DataType
	(*Metadata)(nil),       // 1: gophkeeper.v1.common.Metadata
}
var file_proto_v1_common_proto_depIdxs = []int32{
	0, // 0: gophkeeper.v1.common.Metadata.data_type:type_name -> gophkeeper.v1.common.Metadata.DataType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_common_proto_init() }
func file_proto_v1_common_proto_init() {
	if File_proto_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_common_proto_rawDesc), len(file_proto_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_common_proto_goTypes,
		DependencyIndexes: file_proto_v1_common_proto_depIdxs,
		EnumInfos:         file_proto_v1_common_proto_enumTypes,
		MessageInfos:      file_proto_v1_common_proto_msgTypes,
	}.Build()
	File_proto_v1_common_proto = out.File
	file_proto_v1_common_proto_goTypes = nil
	file_proto_v1_common_proto_depIdxs = nil
}
