// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/talx-hub/gophkeeper/internal/model"
)

// NewMockMetadataRepo creates a new instance of MockMetadataRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataRepo {
	mock := &MockMetadataRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataRepo is an autogenerated mock type for the MetadataRepo type
type MockMetadataRepo struct {
	mock.Mock
}

type MockMetadataRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataRepo) EXPECT() *MockMetadataRepo_Expecter {
	return &MockMetadataRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMetadataRepo
func (_mock *MockMetadataRepo) Create(ctx context.Context, meta *model.Metadata, info model.ObjectInfo, loc model.ObjectLocator) (model.DataID, error) {
	ret := _mock.Called(ctx, meta, info, loc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.DataID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Metadata, model.ObjectInfo, model.ObjectLocator) (model.DataID, error)); ok {
		return returnFunc(ctx, meta, info, loc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Metadata, model.ObjectInfo, model.ObjectLocator) model.DataID); ok {
		r0 = returnFunc(ctx, meta, info, loc)
	} else {
		r0 = ret.Get(0).(model.DataID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Metadata, model.ObjectInfo, model.ObjectLocator) error); ok {
		r1 = returnFunc(ctx, meta, info, loc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMetadataRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *model.Metadata
//   - info model.ObjectInfo
//   - loc model.ObjectLocator
func (_e *MockMetadataRepo_Expecter) Create(ctx interface{}, meta interface{}, info interface{}, loc interface{}) *MockMetadataRepo_Create_Call {
	return &MockMetadataRepo_Create_Call{Call: _e.mock.On("Create", ctx, meta, info, loc)}
}

func (_c *MockMetadataRepo_Create_Call) Run(run func(ctx context.Context, meta *model.Metadata, info model.ObjectInfo, loc model.ObjectLocator)) *MockMetadataRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Metadata
		if args[1] != nil {
			arg1 = args[1].(*model.Metadata)
		}
		var arg2 model.ObjectInfo
		if args[2] != nil {
			arg2 = args[2].(model.ObjectInfo)
		}
		var arg3 model.ObjectLocator
		if args[3] != nil {
			arg3 = args[3].(model.ObjectLocator)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMetadataRepo_Create_Call) Return(dataID model.DataID, err error) *MockMetadataRepo_Create_Call {
	_c.Call.Return(dataID, err)
	return _c
}

func (_c *MockMetadataRepo_Create_Call) RunAndReturn(run func(ctx context.Context, meta *model.Metadata, info model.ObjectInfo, loc model.ObjectLocator) (model.DataID, error)) *MockMetadataRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockMetadataRepo
func (_mock *MockMetadataRepo) Delete(ctx context.Context, userID model.UserID, id model.DataID) (model.ObjectLocator, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 model.ObjectLocator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID, model.DataID) (model.ObjectLocator, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID, model.DataID) model.ObjectLocator); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(model.ObjectLocator)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserID, model.DataID) error); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMetadataRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model.UserID
//   - id model.DataID
func (_e *MockMetadataRepo_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockMetadataRepo_Delete_Call {
	return &MockMetadataRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockMetadataRepo_Delete_Call) Run(run func(ctx context.Context, userID model.UserID, id model.DataID)) *MockMetadataRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserID
		if args[1] != nil {
			arg1 = args[1].(model.UserID)
		}
		var arg2 model.DataID
		if args[2] != nil {
			arg2 = args[2].(model.DataID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataRepo_Delete_Call) Return(objectLocator model.ObjectLocator, err error) *MockMetadataRepo_Delete_Call {
	_c.Call.Return(objectLocator, err)
	return _c
}

func (_c *MockMetadataRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, userID model.UserID, id model.DataID) (model.ObjectLocator, error)) *MockMetadataRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockMetadataRepo
func (_mock *MockMetadataRepo) Get(ctx context.Context, userID model.UserID, id model.DataID) (model.Metadata, model.ObjectLocator, error) {
	ret := _mock.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Metadata
	var r1 model.ObjectLocator
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID, model.DataID) (model.Metadata, model.ObjectLocator, error)); ok {
		return returnFunc(ctx, userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID, model.DataID) model.Metadata); ok {
		r0 = returnFunc(ctx, userID, id)
	} else {
		r0 = ret.Get(0).(model.Metadata)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserID, model.DataID) model.ObjectLocator); ok {
		r1 = returnFunc(ctx, userID, id)
	} else {
		r1 = ret.Get(1).(model.ObjectLocator)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, model.UserID, model.DataID) error); ok {
		r2 = returnFunc(ctx, userID, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMetadataRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMetadataRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model.UserID
//   - id model.DataID
func (_e *MockMetadataRepo_Expecter) Get(ctx interface{}, userID interface{}, id interface{}) *MockMetadataRepo_Get_Call {
	return &MockMetadataRepo_Get_Call{Call: _e.mock.On("Get", ctx, userID, id)}
}

func (_c *MockMetadataRepo_Get_Call) Run(run func(ctx context.Context, userID model.UserID, id model.DataID)) *MockMetadataRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserID
		if args[1] != nil {
			arg1 = args[1].(model.UserID)
		}
		var arg2 model.DataID
		if args[2] != nil {
			arg2 = args[2].(model.DataID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataRepo_Get_Call) Return(metadata model.Metadata, objectLocator model.ObjectLocator, err error) *MockMetadataRepo_Get_Call {
	_c.Call.Return(metadata, objectLocator, err)
	return _c
}

func (_c *MockMetadataRepo_Get_Call) RunAndReturn(run func(ctx context.Context, userID model.UserID, id model.DataID) (model.Metadata, model.ObjectLocator, error)) *MockMetadataRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockMetadataRepo
func (_mock *MockMetadataRepo) ListByUser(ctx context.Context, userID model.UserID) ([]model.MetaLoc, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.MetaLoc
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID) ([]model.MetaLoc, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserID) []model.MetaLoc); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MetaLoc)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataRepo_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockMetadataRepo_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID model.UserID
func (_e *MockMetadataRepo_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockMetadataRepo_ListByUser_Call {
	return &MockMetadataRepo_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockMetadataRepo_ListByUser_Call) Run(run func(ctx context.Context, userID model.UserID)) *MockMetadataRepo_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserID
		if args[1] != nil {
			arg1 = args[1].(model.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataRepo_ListByUser_Call) Return(metaLocs []model.MetaLoc, err error) *MockMetadataRepo_ListByUser_Call {
	_c.Call.Return(metaLocs, err)
	return _c
}

func (_c *MockMetadataRepo_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID model.UserID) ([]model.MetaLoc, error)) *MockMetadataRepo_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}
