// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
	"github.com/talx-hub/gophkeeper/internal/model"
)

// NewMockObjectRepo creates a new instance of MockObjectRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectRepo {
	mock := &MockObjectRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectRepo is an autogenerated mock type for the ObjectRepo type
type MockObjectRepo struct {
	mock.Mock
}

type MockObjectRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectRepo) EXPECT() *MockObjectRepo_Expecter {
	return &MockObjectRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockObjectRepo
func (_mock *MockObjectRepo) Delete(ctx context.Context, loc model.ObjectLocator) error {
	ret := _mock.Called(ctx, loc)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ObjectLocator) error); ok {
		r0 = returnFunc(ctx, loc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockObjectRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - loc model.ObjectLocator
func (_e *MockObjectRepo_Expecter) Delete(ctx interface{}, loc interface{}) *MockObjectRepo_Delete_Call {
	return &MockObjectRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, loc)}
}

func (_c *MockObjectRepo_Delete_Call) Run(run func(ctx context.Context, loc model.ObjectLocator)) *MockObjectRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ObjectLocator
		if args[1] != nil {
			arg1 = args[1].(model.ObjectLocator)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectRepo_Delete_Call) Return(err error) *MockObjectRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, loc model.ObjectLocator) error) *MockObjectRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockObjectRepo
func (_mock *MockObjectRepo) Get(ctx context.Context, loc model.ObjectLocator) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, loc)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ObjectLocator) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, loc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ObjectLocator) io.ReadCloser); ok {
		r0 = returnFunc(ctx, loc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ObjectLocator) error); ok {
		r1 = returnFunc(ctx, loc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockObjectRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - loc model.ObjectLocator
func (_e *MockObjectRepo_Expecter) Get(ctx interface{}, loc interface{}) *MockObjectRepo_Get_Call {
	return &MockObjectRepo_Get_Call{Call: _e.mock.On("Get", ctx, loc)}
}

func (_c *MockObjectRepo_Get_Call) Run(run func(ctx context.Context, loc model.ObjectLocator)) *MockObjectRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ObjectLocator
		if args[1] != nil {
			arg1 = args[1].(model.ObjectLocator)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectRepo_Get_Call) Return(readCloser io.ReadCloser, err error) *MockObjectRepo_Get_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockObjectRepo_Get_Call) RunAndReturn(run func(ctx context.Context, loc model.ObjectLocator) (io.ReadCloser, error)) *MockObjectRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockObjectRepo
func (_mock *MockObjectRepo) Put(ctx context.Context, meta *model.Metadata, r io.Reader, size uint64, sha256 []byte) (model.ObjectLocator, error) {
	ret := _mock.Called(ctx, meta, r, size, sha256)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 model.ObjectLocator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Metadata, io.Reader, uint64, []byte) (model.ObjectLocator, error)); ok {
		return returnFunc(ctx, meta, r, size, sha256)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Metadata, io.Reader, uint64, []byte) model.ObjectLocator); ok {
		r0 = returnFunc(ctx, meta, r, size, sha256)
	} else {
		r0 = ret.Get(0).(model.ObjectLocator)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Metadata, io.Reader, uint64, []byte) error); ok {
		r1 = returnFunc(ctx, meta, r, size, sha256)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectRepo_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockObjectRepo_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *model.Metadata
//   - r io.Reader
//   - size uint64
//   - sha256 []byte
func (_e *MockObjectRepo_Expecter) Put(ctx interface{}, meta interface{}, r interface{}, size interface{}, sha256 interface{}) *MockObjectRepo_Put_Call {
	return &MockObjectRepo_Put_Call{Call: _e.mock.On("Put", ctx, meta, r, size, sha256)}
}

func (_c *MockObjectRepo_Put_Call) Run(run func(ctx context.Context, meta *model.Metadata, r io.Reader, size uint64, sha256 []byte)) *MockObjectRepo_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Metadata
		if args[1] != nil {
			arg1 = args[1].(*model.Metadata)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockObjectRepo_Put_Call) Return(objectLocator model.ObjectLocator, err error) *MockObjectRepo_Put_Call {
	_c.Call.Return(objectLocator, err)
	return _c
}

func (_c *MockObjectRepo_Put_Call) RunAndReturn(run func(ctx context.Context, meta *model.Metadata, r io.Reader, size uint64, sha256 []byte) (model.ObjectLocator, error)) *MockObjectRepo_Put_Call {
	_c.Call.Return(run)
	return _c
}
