// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/talx-hub/gophkeeper/internal/model"
)

// NewMockRefreshTokenStorage creates a new instance of MockRefreshTokenStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenStorage {
	mock := &MockRefreshTokenStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshTokenStorage is an autogenerated mock type for the RefreshTokenStorage type
type MockRefreshTokenStorage struct {
	mock.Mock
}

type MockRefreshTokenStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenStorage) EXPECT() *MockRefreshTokenStorage_Expecter {
	return &MockRefreshTokenStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRefreshTokenStorage
func (_mock *MockRefreshTokenStorage) Delete(ctx context.Context, tokenID string) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRefreshTokenStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockRefreshTokenStorage_Expecter) Delete(ctx interface{}, tokenID interface{}) *MockRefreshTokenStorage_Delete_Call {
	return &MockRefreshTokenStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, tokenID)}
}

func (_c *MockRefreshTokenStorage_Delete_Call) Run(run func(ctx context.Context, tokenID string)) *MockRefreshTokenStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenStorage_Delete_Call) Return(err error) *MockRefreshTokenStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, tokenID string) error) *MockRefreshTokenStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRefreshTokenStorage
func (_mock *MockRefreshTokenStorage) Save(ctx context.Context, tokenID string, userID model.UserID, expiresAt time.Time) error {
	ret := _mock.Called(ctx, tokenID, userID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.UserID, time.Time) error); ok {
		r0 = returnFunc(ctx, tokenID, userID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRefreshTokenStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
//   - userID model.UserID
//   - expiresAt time.Time
func (_e *MockRefreshTokenStorage_Expecter) Save(ctx interface{}, tokenID interface{}, userID interface{}, expiresAt interface{}) *MockRefreshTokenStorage_Save_Call {
	return &MockRefreshTokenStorage_Save_Call{Call: _e.mock.On("Save", ctx, tokenID, userID, expiresAt)}
}

func (_c *MockRefreshTokenStorage_Save_Call) Run(run func(ctx context.Context, tokenID string, userID model.UserID, expiresAt time.Time)) *MockRefreshTokenStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.UserID
		if args[2] != nil {
			arg2 = args[2].(model.UserID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRefreshTokenStorage_Save_Call) Return(err error) *MockRefreshTokenStorage_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenStorage_Save_Call) RunAndReturn(run func(ctx context.Context, tokenID string, userID model.UserID, expiresAt time.Time) error) *MockRefreshTokenStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockRefreshTokenStorage
func (_mock *MockRefreshTokenStorage) Validate(ctx context.Context, tokenID string) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenStorage_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockRefreshTokenStorage_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockRefreshTokenStorage_Expecter) Validate(ctx interface{}, tokenID interface{}) *MockRefreshTokenStorage_Validate_Call {
	return &MockRefreshTokenStorage_Validate_Call{Call: _e.mock.On("Validate", ctx, tokenID)}
}

func (_c *MockRefreshTokenStorage_Validate_Call) Run(run func(ctx context.Context, tokenID string)) *MockRefreshTokenStorage_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenStorage_Validate_Call) Return(err error) *MockRefreshTokenStorage_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenStorage_Validate_Call) RunAndReturn(run func(ctx context.Context, tokenID string) error) *MockRefreshTokenStorage_Validate_Call {
	_c.Call.Return(run)
	return _c
}
