// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: proto/v1/metadata/metadata.proto

package metadatapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata_DataType int32

const (
	Metadata_DATA_TYPE_UNSPECIFIED Metadata_DataType = 0
	Metadata_DATA_TYPE_AUTH        Metadata_DataType = 1
	Metadata_DATA_TYPE_CARD        Metadata_DataType = 2
	Metadata_DATA_TYPE_BINARY      Metadata_DataType = 3
)

// Enum value maps for Metadata_DataType.
var (
	Metadata_DataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_AUTH",
		2: "DATA_TYPE_CARD",
		3: "DATA_TYPE_BINARY",
	}
	Metadata_DataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED": 0,
		"DATA_TYPE_AUTH":        1,
		"DATA_TYPE_CARD":        2,
		"DATA_TYPE_BINARY":      3,
	}
)

func (x Metadata_DataType) Enum() *Metadata_DataType {
	p := new(Metadata_DataType)
	*p = x
	return p
}

func (x Metadata_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metadata_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_metadata_metadata_proto_enumTypes[0].Descriptor()
}

func (Metadata_DataType) Type() protoreflect.EnumType {
	return &file_proto_v1_metadata_metadata_proto_enumTypes[0]
}

func (x Metadata_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metadata_DataType.Descriptor instead.
func (Metadata_DataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_metadata_metadata_proto_rawDescGZIP(), []int{0, 0}
}

// Метаданные, описывающие объект данных.
// Здесь хранится основная информация для идентификации объекта.
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      *Metadata_DataType     `protobuf:"varint,1,opt,name=data_type,json=dataType,enum=gophkeeper.v1.metadata.Metadata_DataType" json:"data_type,omitempty"` // Один из типов хранимых данных
	Id            *int64                 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`                                                                           // Уникальный идентификатор записи
	Name          *string                `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`                                                                        // Человекочитаемое имя
	Description   *string                `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`                                                          // Заметка
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`                                             // Время создания
	ChunkMetadata *ChunkMetadata         `protobuf:"bytes,6,opt,name=chunk_metadata,json=chunkMetadata" json:"chunk_metadata,omitempty"`                                 // Если data_type == DATA_TYPE_BINARY, это поле заполняется данными
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_v1_metadata_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_metadata_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_v1_metadata_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetDataType() Metadata_DataType {
	if x != nil && x.DataType != nil {
		return *x.DataType
	}
	return Metadata_DATA_TYPE_UNSPECIFIED
}

func (x *Metadata) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Metadata) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Metadata) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Metadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Metadata) GetChunkMetadata() *ChunkMetadata {
	if x != nil {
		return x.ChunkMetadata
	}
	return nil
}

type ChunkMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        *uint64                `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`                                // смещение байт в объекте (0-based)
	ObjectSize    *uint64                `protobuf:"varint,2,opt,name=object_size,json=objectSize" json:"object_size,omitempty"`      // общий размер объекта в байтах
	Last          *bool                  `protobuf:"varint,3,opt,name=last" json:"last,omitempty"`                                    // последний ли чанк
	Crc32C        *uint32                `protobuf:"varint,4,opt,name=crc32c" json:"crc32c,omitempty"`                                // CRC для чанка
	ObjectSha256  []byte                 `protobuf:"bytes,5,opt,name=object_sha256,json=objectSha256" json:"object_sha256,omitempty"` // 32 байта;  Хэш всего файла — одинаков в каждом чанке
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkMetadata) Reset() {
	*x = ChunkMetadata{}
	mi := &file_proto_v1_metadata_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkMetadata) ProtoMessage() {}

func (x *ChunkMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_metadata_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkMetadata.ProtoReflect.Descriptor instead.
func (*ChunkMetadata) Descriptor() ([]byte, []int) {
	return file_proto_v1_metadata_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkMetadata) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ChunkMetadata) GetObjectSize() uint64 {
	if x != nil && x.ObjectSize != nil {
		return *x.ObjectSize
	}
	return 0
}

func (x *ChunkMetadata) GetLast() bool {
	if x != nil && x.Last != nil {
		return *x.Last
	}
	return false
}

func (x *ChunkMetadata) GetCrc32C() uint32 {
	if x != nil && x.Crc32C != nil {
		return *x.Crc32C
	}
	return 0
}

func (x *ChunkMetadata) GetObjectSha256() []byte {
	if x != nil {
		return x.ObjectSha256
	}
	return nil
}

var File_proto_v1_metadata_metadata_proto protoreflect.FileDescriptor

const file_proto_v1_metadata_metadata_proto_rawDesc = "" +
	"\n" +
	" proto/v1/metadata/metadata.proto\x12\x16gophkeeper.v1.metadata\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x03\n" +
	"\bMetadata\x12F\n" +
	"\tdata_type\x18\x01 \x01(\x0e2).gophkeeper.v1.metadata.Metadata.DataTypeR\bdataType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12L\n" +
	"\x0echunk_metadata\x18\x06 \x01(\v2%.gophkeeper.v1.metadata.ChunkMetadataR\rchunkMetadata\"c\n" +
	"\bDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDATA_TYPE_AUTH\x10\x01\x12\x12\n" +
	"\x0eDATA_TYPE_CARD\x10\x02\x12\x14\n" +
	"\x10DATA_TYPE_BINARY\x10\x03\"\x99\x01\n" +
	"\rChunkMetadata\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x1f\n" +
	"\vobject_size\x18\x02 \x01(\x04R\n" +
	"objectSize\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\x12\x16\n" +
	"\x06crc32c\x18\x04 \x01(\rR\x06crc32c\x12#\n" +
	"\robject_sha256\x18\x05 \x01(\fR\fobjectSha256B=Z;github.com/talx-hub/gophkeeper/proto/v1/metadata;metadatapbb\beditionsp\xe8\a"

var (
	file_proto_v1_metadata_metadata_proto_rawDescOnce sync.Once
	file_proto_v1_metadata_metadata_proto_rawDescData []byte
)

func file_proto_v1_metadata_metadata_proto_rawDescGZIP() []byte {
	file_proto_v1_metadata_metadata_proto_rawDescOnce.Do(func() {
		file_proto_v1_metadata_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_metadata_metadata_proto_rawDesc), len(file_proto_v1_metadata_metadata_proto_rawDesc)))
	})
	return file_proto_v1_metadata_metadata_proto_rawDescData
}

var file_proto_v1_metadata_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_metadata_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_metadata_metadata_proto_goTypes = []any{
	(Metadata_DataType)(0),        // 0: gophkeeper.v1.metadata.Metadata.DataType
	(*Metadata)(nil),              // 1: gophkeeper.v1.metadata.Metadata
	(*ChunkMetadata)(nil),         // 2: gophkeeper.v1.metadata.ChunkMetadata
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_v1_metadata_metadata_proto_depIdxs = []int32{
	0, // 0: gophkeeper.v1.metadata.Metadata.data_type:type_name -> gophkeeper.v1.metadata.Metadata.DataType
	3, // 1: gophkeeper.v1.metadata.Metadata.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: gophkeeper.v1.metadata.Metadata.chunk_metadata:type_name -> gophkeeper.v1.metadata.ChunkMetadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_metadata_metadata_proto_init() }
func file_proto_v1_metadata_metadata_proto_init() {
	if File_proto_v1_metadata_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_metadata_metadata_proto_rawDesc), len(file_proto_v1_metadata_metadata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_metadata_metadata_proto_goTypes,
		DependencyIndexes: file_proto_v1_metadata_metadata_proto_depIdxs,
		EnumInfos:         file_proto_v1_metadata_metadata_proto_enumTypes,
		MessageInfos:      file_proto_v1_metadata_metadata_proto_msgTypes,
	}.Build()
	File_proto_v1_metadata_metadata_proto = out.File
	file_proto_v1_metadata_metadata_proto_goTypes = nil
	file_proto_v1_metadata_metadata_proto_depIdxs = nil
}
