@startuml
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define PK(field) <u>field</u>
!define FK(field) <i>field</i>

skinparam class {
  BackgroundColor<<T>> PaleGoldenRod
  ArrowColor Black
  BorderColor Black
}
skinparam linetype ortho

Table(users, "users") {
  PK(id) : UUID
  hash : TEXT
}


Table(passwords, "passwords") {
  PK(id) : UUID
  FK(id_user) : UUID
  hash : TEXT
}


Table(types, "types") {
  PK(id) : INT
  name : VARCHAR(30)
}


Table(metadata, "metadata") {
  PK(id) : INT
  FK(id_user) : UUID
  FK(id_type) : INT
  note : TEXT
}


Table(refresh_tokens, "refresh_tokens") {
  PK(id) : UUID
  FK(id_user) : UUID
  expires_at : timestamptz
}


' Отношения
users "1" <-- "0..*" passwords : id_user\n(ON DELETE CASCADE)
users "1" <-- "0..*" metadata : id_user\n(ON DELETE RESTRICT)
users "1" <-- "0..*" refresh_tokens : id_user\n(ON DELETE CASCADE)
metadata "0..*" -->"1" types : id_type (ON DELETE RESTRICT)



@enduml
