// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: metadata.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMetadata = `-- name: DeleteMetadata :one
DELETE FROM objects
WHERE id = $1
RETURNING storage_locator
`

func (q *Queries) DeleteMetadata(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteMetadata, id)
	var storage_locator string
	err := row.Scan(&storage_locator)
	return storage_locator, err
}

const getMetadata = `-- name: GetMetadata :one
SELECT
    o.id,
    o.storage_locator,
    dt.name AS data_type_name,
    o.name AS object_name,
    o.description,
    o.created_at
FROM objects o
    JOIN public.data_types dt on o.id_data_type = dt.id
WHERE o.id = $1
`

type GetMetadataRow struct {
	ID             pgtype.UUID
	StorageLocator string
	DataTypeName   string
	ObjectName     string
	Description    pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetMetadata(ctx context.Context, id pgtype.UUID) (GetMetadataRow, error) {
	row := q.db.QueryRow(ctx, getMetadata, id)
	var i GetMetadataRow
	err := row.Scan(
		&i.ID,
		&i.StorageLocator,
		&i.DataTypeName,
		&i.ObjectName,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listByUser = `-- name: ListByUser :many
SELECT
    o.id,
    o.storage_locator,
    dt.name AS data_type_name,
    o.name AS object_name,
    o.description,
    o.created_at
FROM objects o
    JOIN public.data_types dt on o.id_data_type = dt.id
WHERE o.user_id = $1
`

type ListByUserRow struct {
	ID             pgtype.UUID
	StorageLocator string
	DataTypeName   string
	ObjectName     string
	Description    pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ListByUser(ctx context.Context, userID pgtype.UUID) ([]ListByUserRow, error) {
	rows, err := q.db.Query(ctx, listByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListByUserRow
	for rows.Next() {
		var i ListByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.StorageLocator,
			&i.DataTypeName,
			&i.ObjectName,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putMetadata = `-- name: PutMetadata :one
INSERT INTO objects (user_id, id_data_type, name, description, storage_locator)
VALUES (
           $1::uuid,
           (SELECT id
            FROM data_types
            WHERE public.data_types.name = $2),
           $3,
           $4,
           $5
       )
RETURNING id
`

type PutMetadataParams struct {
	UserID         pgtype.UUID
	DataTypeName   string
	ObjectName     string
	Description    pgtype.Text
	StorageLocator string
}

func (q *Queries) PutMetadata(ctx context.Context, arg PutMetadataParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, putMetadata,
		arg.UserID,
		arg.DataTypeName,
		arg.ObjectName,
		arg.Description,
		arg.StorageLocator,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
