// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DataType struct {
	ID   int32
	Name string
}

type FileChunk struct {
	ObjectsID  pgtype.UUID
	ChunkIndex int32
	Length     int32
	StorageKey string
}

type Object struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	DataType    int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type RefreshToken struct {
	ID        int32
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

type SecretBlob struct {
	ID        pgtype.UUID
	ObjectsID pgtype.UUID
	Sealed    []byte
}

type User struct {
	ID          pgtype.UUID
	LoginHash   []byte
	PasswordPhc string
}
