// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChunkManifest struct {
	ObjectsID  pgtype.UUID
	BlobID     pgtype.UUID
	ChunkIndex int32
	Length     int32
}

type DataType struct {
	ID   int32
	Name string
}

type Object struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	IDDataType     int32
	Name           string
	Description    pgtype.Text
	StorageLocator string
	CreatedAt      pgtype.Timestamptz
}

type RefreshToken struct {
	ID        int32
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

type SecretBlob struct {
	ID        pgtype.UUID
	ObjectsID pgtype.UUID
	Sealed    []byte
}

type User struct {
	ID          pgtype.UUID
	LoginHash   []byte
	PasswordPhc string
}
