// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: objects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteObject = `-- name: DeleteObject :exec
DELETE FROM secret_blobs
WHERE cm.objects_id = (
    SELECT id FROM objects
    WHERE storage_locator = $1
)
`

func (q *Queries) DeleteObject(ctx context.Context, storageLocator string) error {
	_, err := q.db.Exec(ctx, deleteObject, storageLocator)
	return err
}

const insertBlob = `-- name: InsertBlob :one
INSERT INTO secret_blobs(objects_id, sealed)
VALUES ($1, $2)
RETURNING id
`

type InsertBlobParams struct {
	ObjectsID pgtype.UUID
	Sealed    []byte
}

func (q *Queries) InsertBlob(ctx context.Context, arg InsertBlobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertBlob, arg.ObjectsID, arg.Sealed)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const putManifest = `-- name: PutManifest :exec
INSERT INTO chunk_manifest(objects_id, blob_id, chunk_index, length)
VALUES ($1, $2, $3, $4)
`

type PutManifestParams struct {
	ObjectsID  pgtype.UUID
	BlobID     pgtype.UUID
	ChunkIndex int32
	Length     int32
}

func (q *Queries) PutManifest(ctx context.Context, arg PutManifestParams) error {
	_, err := q.db.Exec(ctx, putManifest,
		arg.ObjectsID,
		arg.BlobID,
		arg.ChunkIndex,
		arg.Length,
	)
	return err
}
