// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteToken, tokenHash)
	return err
}

const save = `-- name: Save :exec
INSERT INTO refresh_tokens(user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (token_hash) DO UPDATE
    SET user_id = EXCLUDED.user_id,
        expires_at = EXCLUDED.expires_at
`

type SaveParams struct {
	UserID    pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.Exec(ctx, save, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const validate = `-- name: Validate :one
SELECT EXISTS (
    SELECT 1
    FROM refresh_tokens
    WHERE token_hash = $1 AND
          user_id = $2 AND
          expires_at > NOW()
) AS found
`

type ValidateParams struct {
	TokenHash []byte
	UserID    pgtype.UUID
}

func (q *Queries) Validate(ctx context.Context, arg ValidateParams) (bool, error) {
	row := q.db.QueryRow(ctx, validate, arg.TokenHash, arg.UserID)
	var found bool
	err := row.Scan(&found)
	return found, err
}
