// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO users(login_hash, password_phc)
VALUES ($1, $2)
RETURNING id
`

type CreateParams struct {
	LoginHash   []byte
	PasswordPhc string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, create, arg.LoginHash, arg.PasswordPhc)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findByLogin = `-- name: FindByLogin :one
SELECT id, password_phc
FROM users
WHERE login_hash == $1
`

type FindByLoginRow struct {
	ID          pgtype.UUID
	PasswordPhc string
}

func (q *Queries) FindByLogin(ctx context.Context, loginHash []byte) (FindByLoginRow, error) {
	row := q.db.QueryRow(ctx, findByLogin, loginHash)
	var i FindByLoginRow
	err := row.Scan(&i.ID, &i.PasswordPhc)
	return i, err
}
