// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: proto/v1/auth/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на регистрацию нового пользователя.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthData      *AuthData              `protobuf:"bytes,1,opt,name=auth_data,json=authData" json:"auth_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_v1_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAuthData() *AuthData {
	if x != nil {
		return x.AuthData
	}
	return nil
}

// Ответ с токенами аутентификации после регистрации.
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *Credentials           `protobuf:"bytes,1,opt,name=credentials" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_v1_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// Запрос на вход пользователя.
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthData      *AuthData              `protobuf:"bytes,1,opt,name=auth_data,json=authData" json:"auth_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_v1_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetAuthData() *AuthData {
	if x != nil {
		return x.AuthData
	}
	return nil
}

// Ответ с токенами аутентификации после входа.
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *Credentials           `protobuf:"bytes,1,opt,name=credentials" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_v1_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// Запрос на выход (logout).
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  *RefreshToken          `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_v1_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutRequest) GetRefreshToken() *RefreshToken {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

// Данные аутентификации пользователя.
type AuthData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         *string                `protobuf:"bytes,1,opt,name=login" json:"login,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthData) Reset() {
	*x = AuthData{}
	mi := &file_proto_v1_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthData) ProtoMessage() {}

func (x *AuthData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthData.ProtoReflect.Descriptor instead.
func (*AuthData) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *AuthData) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

func (x *AuthData) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

// Учетные данные, включающие access и refresh токены.
type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *AccessToken           `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	RefreshToken  *RefreshToken          `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_proto_v1_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *Credentials) GetAccessToken() *AccessToken {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *Credentials) GetRefreshToken() *RefreshToken {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

// Access токен, используемый для авторизации запросов.
type AccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *string                `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_proto_v1_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *AccessToken) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

// Refresh токен, используемый для обновления access токена.
type RefreshToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  *string                `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshToken) Reset() {
	*x = RefreshToken{}
	mi := &file_proto_v1_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshToken) ProtoMessage() {}

func (x *RefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshToken.ProtoReflect.Descriptor instead.
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshToken) GetRefreshToken() string {
	if x != nil && x.RefreshToken != nil {
		return *x.RefreshToken
	}
	return ""
}

var File_proto_v1_auth_auth_proto protoreflect.FileDescriptor

const file_proto_v1_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x18proto/v1/auth/auth.proto\x12\x12gophkeeper.v1.auth\x1a\x1bgoogle/protobuf/empty.proto\"L\n" +
	"\x0fRegisterRequest\x129\n" +
	"\tauth_data\x18\x01 \x01(\v2\x1c.gophkeeper.v1.auth.AuthDataR\bauthData\"U\n" +
	"\x10RegisterResponse\x12A\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1f.gophkeeper.v1.auth.CredentialsR\vcredentials\"I\n" +
	"\fLoginRequest\x129\n" +
	"\tauth_data\x18\x01 \x01(\v2\x1c.gophkeeper.v1.auth.AuthDataR\bauthData\"R\n" +
	"\rLoginResponse\x12A\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1f.gophkeeper.v1.auth.CredentialsR\vcredentials\"V\n" +
	"\rLogoutRequest\x12E\n" +
	"\rrefresh_token\x18\x01 \x01(\v2 .gophkeeper.v1.auth.RefreshTokenR\frefreshToken\"<\n" +
	"\bAuthData\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x98\x01\n" +
	"\vCredentials\x12B\n" +
	"\faccess_token\x18\x01 \x01(\v2\x1f.gophkeeper.v1.auth.AccessTokenR\vaccessToken\x12E\n" +
	"\rrefresh_token\x18\x02 \x01(\v2 .gophkeeper.v1.auth.RefreshTokenR\frefreshToken\"0\n" +
	"\vAccessToken\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"3\n" +
	"\fRefreshToken\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken2\xf7\x01\n" +
	"\vAuthService\x12U\n" +
	"\bRegister\x12#.gophkeeper.v1.auth.RegisterRequest\x1a$.gophkeeper.v1.auth.RegisterResponse\x12L\n" +
	"\x05Login\x12 .gophkeeper.v1.auth.LoginRequest\x1a!.gophkeeper.v1.auth.LoginResponse\x12C\n" +
	"\x06Logout\x12!.gophkeeper.v1.auth.LogoutRequest\x1a\x16.google.protobuf.EmptyB<Z:github.com/talx-hub/gophkeeper/internal/api/v1/auth;authpbb\beditionsp\xe8\a"

var (
	file_proto_v1_auth_auth_proto_rawDescOnce sync.Once
	file_proto_v1_auth_auth_proto_rawDescData []byte
)

func file_proto_v1_auth_auth_proto_rawDescGZIP() []byte {
	file_proto_v1_auth_auth_proto_rawDescOnce.Do(func() {
		file_proto_v1_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_auth_auth_proto_rawDesc), len(file_proto_v1_auth_auth_proto_rawDesc)))
	})
	return file_proto_v1_auth_auth_proto_rawDescData
}

var file_proto_v1_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_v1_auth_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: gophkeeper.v1.auth.RegisterRequest
	(*RegisterResponse)(nil), // 1: gophkeeper.v1.auth.RegisterResponse
	(*LoginRequest)(nil),     // 2: gophkeeper.v1.auth.LoginRequest
	(*LoginResponse)(nil),    // 3: gophkeeper.v1.auth.LoginResponse
	(*LogoutRequest)(nil),    // 4: gophkeeper.v1.auth.LogoutRequest
	(*AuthData)(nil),         // 5: gophkeeper.v1.auth.AuthData
	(*Credentials)(nil),      // 6: gophkeeper.v1.auth.Credentials
	(*AccessToken)(nil),      // 7: gophkeeper.v1.auth.AccessToken
	(*RefreshToken)(nil),     // 8: gophkeeper.v1.auth.RefreshToken
	(*emptypb.Empty)(nil),    // 9: google.protobuf.Empty
}
var file_proto_v1_auth_auth_proto_depIdxs = []int32{
	5,  // 0: gophkeeper.v1.auth.RegisterRequest.auth_data:type_name -> gophkeeper.v1.auth.AuthData
	6,  // 1: gophkeeper.v1.auth.RegisterResponse.credentials:type_name -> gophkeeper.v1.auth.Credentials
	5,  // 2: gophkeeper.v1.auth.LoginRequest.auth_data:type_name -> gophkeeper.v1.auth.AuthData
	6,  // 3: gophkeeper.v1.auth.LoginResponse.credentials:type_name -> gophkeeper.v1.auth.Credentials
	8,  // 4: gophkeeper.v1.auth.LogoutRequest.refresh_token:type_name -> gophkeeper.v1.auth.RefreshToken
	7,  // 5: gophkeeper.v1.auth.Credentials.access_token:type_name -> gophkeeper.v1.auth.AccessToken
	8,  // 6: gophkeeper.v1.auth.Credentials.refresh_token:type_name -> gophkeeper.v1.auth.RefreshToken
	0,  // 7: gophkeeper.v1.auth.AuthService.Register:input_type -> gophkeeper.v1.auth.RegisterRequest
	2,  // 8: gophkeeper.v1.auth.AuthService.Login:input_type -> gophkeeper.v1.auth.LoginRequest
	4,  // 9: gophkeeper.v1.auth.AuthService.Logout:input_type -> gophkeeper.v1.auth.LogoutRequest
	1,  // 10: gophkeeper.v1.auth.AuthService.Register:output_type -> gophkeeper.v1.auth.RegisterResponse
	3,  // 11: gophkeeper.v1.auth.AuthService.Login:output_type -> gophkeeper.v1.auth.LoginResponse
	9,  // 12: gophkeeper.v1.auth.AuthService.Logout:output_type -> google.protobuf.Empty
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_v1_auth_auth_proto_init() }
func file_proto_v1_auth_auth_proto_init() {
	if File_proto_v1_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_auth_auth_proto_rawDesc), len(file_proto_v1_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_auth_auth_proto_goTypes,
		DependencyIndexes: file_proto_v1_auth_auth_proto_depIdxs,
		MessageInfos:      file_proto_v1_auth_auth_proto_msgTypes,
	}.Build()
	File_proto_v1_auth_auth_proto = out.File
	file_proto_v1_auth_auth_proto_goTypes = nil
	file_proto_v1_auth_auth_proto_depIdxs = nil
}
